name: autorelease
on:
  schedule:
    - cron: '0 17 * * 5' # Every Friday at 12pm EST (5pm UTC)
jobs:
  autorelease:
    name: autorelease
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: autorelease
        uses: markelliot/autorelease@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-days: 7
          tag-only: true
